/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQjovYnVpbGRtb3Rpb24vYW5ndWxhci1tb2R1bGUtc3RhcnRlci9zcmMvYXBwL3N0YXJ0ZXIvaGVsbG8td29ybGQvaGVsbG8td29ybGQuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9COi9idWlsZG1vdGlvbi9hbmd1bGFyLW1vZHVsZS1zdGFydGVyL3NyYy9hcHAvc3RhcnRlci9oZWxsby13b3JsZC9oZWxsby13b3JsZC5jb21wb25lbnQuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
